version: '3'

tasks:
  tsc:
    method: timestamp
    cmds:
      - npx tsc -d
    sources:
      - src/**/*.ts
    generates:
      - dist/**/*.js

  tap:
    method: timestamp
    deps: [tsc]
    cmds:
      - npx tap {{.CLI_ARGS}}

  c8tap:
    method: timestamp
    deps: [tsc]
    cmds:
      - |
        c8 npx tap -t600 test/*.tap.*js {{.CLI_ARGS}}
        npm run c8rephtml

  clean:
    method: none
    cmds:
      - rm -r dist
