version: '3'

tasks:
    tsc:
        method: timestamp
        cmds:
            - npx tsc -d
        sources:
            - src/**/*.ts
        generates:
            - dist/**/*.js

    tap:
        method: none
        deps: [tsc]
        cmds:
            - npx tap {{.CLI_ARGS}}

    c8tap:
        method: none
        deps: [tsc]
        cmds:
            - |
                c8 tap {{.CLI_ARGS}}
                npm run c8rephtml
