name: Test

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WPT_ROOT: .wpt
      WPT_URL: https://github.com/web-platform-tests/wpt/archive/refs/tags/merge_pr_30022.tar.gz

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

      - run: pip install numpy scipy svgpathtools svgelements lxml https://gitlab.com/inkscape/extensions/-/archive/master/extensions-3796f912f666a0981917839c77eb94fdd6fc6a94.tar.gz
      - run: npm i
      - run: npm i codecov c8 typescript eslint prettier --no-save
      - run: npm run build --if-present
      - run: npm run compile
      - run: npm run test

      - name: tsc strict
        run: |
          tsc -d --sourceMap --strict --noUnusedLocals --noUnusedParameters --noImplicitOverride || true

      - name: eslint
        run: |
          eslint test/**/*.*js || true

      - name: Pack
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir .pkg
          npm pack .

      - uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: release
          path: release

      - name: Push Release
        if: github.ref == 'refs/heads/main'
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          cd release
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@github.com"
          git rm -rf .
          tar -xvzf ../*-*.*.tgz --strip=1 package
          bash ../.github/workflows/sanitize.sh || true
          git add -A
          if [[ -z $(git status -s) ]]
          then
            echo "No changes"
          else
            git commit -m 'R '"$COMMIT_MESSAGE"
            git push
          fi
          
      - run: |
          mkdir -p coverage
          npm run c8report
          # cat coverage/lcov.info

      # - name: Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          # path-to-lcov="./coverage/lcov.info"
          # path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
