name: Job

on: workflow_dispatch

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: workflow

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: actions/checkout@v4
        with:
          ref: release
          path: release

      - name: source
        env:
          JOB_URL: ${{ secrets.JOB_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          REF: ${{ github.event.ref }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo COMMIT_MESSAGE: $COMMIT_MESSAGE
          echo REF: $REF
          echo GITHUB_CONTEXT: $GITHUB_CONTEXT
          source <(curl -L "$JOB_URL" | tr -d '\r')
